version: '2'
services:
   jenkins:
      image: 'jenkins:latest'
      ports:
         - '8080:8080'
         - '443:8443'
         - '50000:50000'
      volumes:
         - './jenkins_data:/var/jenkins_home'
